### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [ZintisMay/liri-node-app#1]
Hey Zinitis I couldn't access your liri program because it doesn't have a package.json file. You can create one by typing npm init. After that I would delete your current node dependencies and then re install them and typing --save after it. For example twitter would be npm install twitter --save, request would be npm install request --save. When you do that check out your package.json file and it will add them as a list of your dependencies. After you do that when I clone your repo all I gotta do is type in npm install and all those dependencies will automatically download.

**Comment by ZintisMay** [comment]
Got it. I might not get to fixing it today, but definitely by tomorrow.

**Comment by ZintisMay** [comment]
Ok, I think I did it, we'll see in class.
